name: Benchmark
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/qt/"
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.3.0"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          dir: "${{ github.workspace }}/qt/"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Build Benchmarks
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_APP=OFF -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=ON ..
            cmake --build . --config Release
      - name: Run DatabaseManagerBenchmark
        working-directory: build/benchmarks/Release
        run: |
            windeployqt DatabaseManagerBenchmark.exe --release --no-translations --no-compiler-runtime
            ./DatabaseManagerBenchmark.exe -o results.txt,txt
            more results.txt