name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/qt/"
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.3.0"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2019_64"
          dir: "${{ github.workspace }}/qt/"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Build
        run: |
            mkdir build
            cd build
            cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_APP=ON -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=OFF ..
            cmake --build . --config Release
            windeployqt Tracker-app/Release/Tracker.exe --release --no-translations --no-compiler-runtime --dir Tracker/
            cp Tracker-app/Release/Tracker.exe Tracker/
            7z a tracker-windows-x64.zip Tracker/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tracker-windows-x64.zip
          path: build/tracker-windows-x64.zip
  release:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tracker-windows-x64.zip
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: latest
          files: tracker-windows-x64.zip